# From GAIA L1

task_description: Of the authors (First M. Last) that worked on the paper \"Pie Menus or Linear Menus, Which Is Better?\" in 2015, what was the title of the first paper authored by the one that had authored prior papers?

expected_answer: Mapping Human Oriented Information to Software Agents for Online Systems Usage
