
PageLogger:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL, or NONE.
  path: ./pagelogs/teachability

client:
  model: gpt-4o-2024-08-06
  provider: trapi  # openai, azure_openai, or trapi
  # api_key: sk-  # only for openai
  temperature: 0.8
  max_completion_tokens: 4096
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1.0
  max_retries: 65535
  ChatCompletionClientRecorder:  # Provides record & replay functionality
    enabled: 1  # Only works for AssistantAgent currently
    mode: replay  # record, replay, or pass to use the client without ChatCompletionClientRecorder
    session_name: ./sessions/teachability/session.json

Apprentice:
  name_of_agent_or_team: AssistantAgent  # AssistantAgent or MagenticOneGroupChat
  disable_prefix_caching: 0  # If true, prepends a small random string to the context, to decorrelate repeated runs.
  MemoryController:
    max_train_trials: 2  # 2-10
    max_test_trials: 1  # 1-3
    MemoryBank:
      path: ./memory_bank/teachability
      relevance_conversion_threshold: 1.7
      n_results: 25
      distance_threshold: 100

test:
  task_file: data_files/tasks/autogen_package.yaml  # The task being tested.
  insight_file: data_files/insights/add_topic.yaml  # Advice provided to help solve the task.

evaluations:
  - eval_function:
      function_name: eval_teachability
      module_path: ./eval_functions/eval_teachability.py
    runs:
      - task_file: data_files/tasks/autogen_package.yaml  # The task being tested.
        insight_file: data_files/insights/add_topic.yaml  # Advice provided to help solve the task.
