
PageLogger:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL, or NONE.
  path: ./pagelogs/reasoning_11

#client:
#  model: gpt-4o-2024-08-06
#  provider: trapi  # openai, azure_openai, or trapi
#  # api_key: sk-  # only for openai
#  temperature: 0.8
#  max_completion_tokens: 4096
#  presence_penalty: 0.0
#  frequency_penalty: 0.0
#  top_p: 1.0
#  max_retries: 65535
#  ChatCompletionClientRecorder:  # Provides record & replay functionality
#    enabled: 0  # Only works for AssistantAgent currently
#    mode: replay  # record, replay, or pass to use the client without ChatCompletionClientRecorder
#    session_name: ./sessions/demonstration/session.json

#client:
#  model: gpt-4.1-2025-04-14
#  provider: trapi  # openai, azure_openai, or trapi
#  temperature: 0.8
#  max_completion_tokens: 32000
#  presence_penalty: 0.0
#  frequency_penalty: 0.0
#  top_p: 1.0
#  max_retries: 65535

#client:
#  model: o4-mini-2025-04-16  # gpt-4o-2024-05-13, gpt-4o-2024-08-06, gpt-4o-2024-11-20, o1-preview, o1, etc.
#  provider: trapi  # openai, azure_openai, or trapi
#  reasoning_effort: "medium"  # low, medium, high

client:
  model: sft_16b_phi4_mathv2code5_otcode_oaif_safe_high32_2
  provider: phi  # openai, azure_openai, trapi, or phi
  temperature: 0.8
  max_completion_tokens: 25000
  presence_penalty: 0.0
  frequency_penalty: 0.0
  top_p: 1.0
  max_retries: 65535

Apprentice:
  name_of_agent_or_team: AssistantAgent  # AssistantAgent or MagenticOneGroupChat
  disable_prefix_caching: 1  # If true, prepends a small random string to the context, to decorrelate repeated runs.
  MemoryController:
    max_train_trials: 2  # 2-10
    max_test_trials: 1  # 1-3
    MemoryBank:
      path: ./memory_bank/reasoning
      relevance_conversion_threshold: 1.7
      n_results: 25
      distance_threshold: 100

evaluations:
  - eval_function:
      function_name: eval_reasoning
      module_path: ./eval_functions/eval_reasoning.py
      num_trials: 5  # 1-10
    runs:
      - main_task_file: data_files/tasks/100_vampires.yaml  # The task being tested.
        demo_task_file: data_files/tasks/10_liars.yaml  # A similar but different task.
        demo_solution_file: data_files/insights/liar_advice.yaml  # A demonstration of solving the second.
#      - main_task_file: data_files/tasks/aime/25/0/9.yaml  # The task being tested.
#        demo_task_file: data_files/tasks/aime/25/0/9r.yaml  # A similar but different task.
#        demo_solution_file: data_files/insights/aime/25/0/9r.yaml  # A demonstration of solving the second.
