task_description: 'Let $N$ denote the number of ordered triples of positive integers
  $(a,b,c)$ such that $a,b,c\leq3^6$ and $a^3+b^3+c^3$ is a multiple of $3^7$. Find
  the remainder when $N$ is divided by $1000$.

  (The answer is an integer from 0 to 999 inclusive.)'
expected_answer: '735'
